### PR TITLE
fix issue #12

### LINKED ISSUE #12: no files after "scan folder"
It does not recognize any files in my "Scan folder" Selection

Nextcloud: 25.0.1
it is an "external storage" -> local linux file system. Opening the directory in nextcloud shows the files. File endings are mostly mkv.

Also: Should I scan a directory with only one tv-show or can I scan the directory containing all my shows?

### PR DESCRIPTION
**Pull request by j4ym0**
non admins can not scan or rename

### CODE REVIEW

**Review by wuppiwuppi — COMMENTED** [review]
I believe you need another @NoAdminRequired for the function saveSetting()

See updates in #12

**Comment by j4ym0** [comment]
I did toy with the non admin on settings.

But as the settings are for all users. Original it was designed that all users would use the same API key. Maybe there needs to be an option for a user to customize there own settings.

What do you think?

**Comment by wuppiwuppi** [comment]
An API-Key is always bound to an account. 

Now it depends on your view: does the admin of the next-cloud instance offer that to all users or is every user responsible for his account + api key (I would prefer that ...)

**Comment by j4ym0** [comment]
After much consideration most of the settings should be per user like the file name structure. This is a users preference although group folders could be an issue.

I still believe that an admin CAN share there api key with the whole Nextcloud instance.

I have decided that all users should have there own settings and to be implemented in the future should be Nextcloud wide default settings for api key.

**Pull request merged**
